DROP TABLE IF EXISTS LIVRE;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS EMPRUNT;

CREATE TABLE LIVRE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR,
    auteur VARCHAR,
    disponible VARCHAR
    );

CREATE TABLE UTILISATEUR(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR,
    prenom VARCHAR,
    role VARCHAR
    );

CREATE TABLE EMPRUNT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    utilisateur_Id INT,
    livre_Id INT
    );
